img2sprite: img2sprite.cpp 
	g++ img2sprite.cpp -I../fonts/ -o img2sprite
png2xterm256: png2xterm256.cpp 
	g++ png2xterm256.cpp -I../fonts/ -o png2xterm256
rlecomp: rlecomp.cpp 
	g++ rlecomp.cpp -o rlecomp
